project:
  type: book
  output-dir: ../../docs/part1

book:
  title: "UCI Diabetes Readmission — Statistical Analysis"
  author: "Chad Pickering"
  chapters:
    - index.qmd
    - 01_eda.qmd
    - 02_causal_inference.qmd
    - 03_experimental_design.qmd

execute:
  warning: false
  message: false
  
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true